services:
    cronolink-db:
      image: postgres:17-alpine
      container_name: cronolink-postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - cronolink-network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost -p 5432"]
        interval: 5s
        timeout: 5s
        retries: 5
    cronolink-api:
      build:
        context: .
        dockerfile: src/Cronolink.API/Dockerfile
      ports:
        - "8080:8080"
      env_file:
        - src/Cronolink.API/.env
      depends_on:
        cronolink-db:
          condition: service_healthy
      networks:
        - cronolink-network
volumes:
  postgres_data:
    driver: local
networks:
  cronolink-network:
    driver: bridge